### ISSUE TITLE
Support Django 1.11

### ISSUE THREAD

**Issue by chrisspen** [grantmcconnaughey/django-lazy-tags#2]
This doesn't appear to support Django > 1.9, as trying to load it I get the error:

    ImportError: cannot import name patterns

**Comment by gaxfor** [comment]
When will the version be upgraded? 
0.4.1 not include this commit

**Comment by grantmcconnaughey** [comment]
[Version 0.5.0 is on PyPI now.](https://pypi.python.org/pypi/django-lazy-tags)

**Comment by chrisspen** [comment]
Thanks!
